development:
  adapter: sqlite3
  database: db.sqlite3

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: utf8
  database: sgShowtimesApi
  host: postgres://doymwkhjebqtug:4d50f97e44948aad66cab2ff9bc87b4a71898b901d54a65b1c5d3ca7b5f7cdb4@ec2-50-17-234-234.compute-1.amazonaws.com:5432/d2lq5aus1qd1s0
  password:
